package edu.ntnu.idatt2104.compiler.dto;

import lombok.Getter;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) class for representing a response from the compiler.
 *
 * @author Ramtin Samavat
 * @version 1.0
 * @since Feb 16, 2024
 */
@Getter
@Setter
public class CompilerResponse {
  private String responseCode;

  /**
   * Constructor for CompilerResponse.
   *
   * @param responseCode The response code generated by the compiler.
   */
  public CompilerResponse(String responseCode) {
    this.responseCode = responseCode;
  }
}
